# Generated by Django 2.0 on 2017-12-18 17:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('Monetary', 'Monetary'), ('Item', 'Item'), ('Both', 'Both')], default='Item', max_length=10)),
                ('campaign_name', models.CharField(default='Campaign Name', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=600)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonatorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DonApp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipping_code', models.CharField(blank=True, max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.Campaign')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.DonatorUser')),
            ],
        ),
        migrations.CreateModel(
            name='MonetaryCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DonApp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.MonetaryCampaign')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.DonatorUser')),
            ],
        ),
        migrations.CreateModel(
            name='NGOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600)),
                ('org_phone_num', models.CharField(max_length=15)),
                ('contact_mail', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator])),
                ('org_website_link', models.CharField(max_length=50, validators=[django.core.validators.URLValidator])),
                ('approved', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.ItemDonation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonApp.NGOUser'),
        ),
    ]
