# Generated by Django 2.0 on 2017-12-19 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DonApp', '0002_auto_20171218_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonation',
            name='ngo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_money_donations', to='DonApp.NGOUser'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='DonApp.NGOUser'),
        ),
        migrations.AlterField(
            model_name='donatoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donator_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='DonApp.ItemDonation'),
        ),
        migrations.AlterField(
            model_name='itemcampaign',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_campaign', to='DonApp.Campaign'),
        ),
        migrations.AlterField(
            model_name='itemdonation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_item_donations', to='DonApp.Campaign'),
        ),
        migrations.AlterField(
            model_name='itemdonation',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_donations', to='DonApp.DonatorUser'),
        ),
        migrations.AlterField(
            model_name='monetarycampaign',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monetary_campaign', to='DonApp.Campaign'),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_money_donations', to='DonApp.MonetaryCampaign'),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_donations', to='DonApp.DonatorUser'),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
