# Generated by Django 2.0 on 2017-12-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DonApp', '0003_auto_20171219_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_money_donations', to='DonApp.Campaign'),
        ),
    ]
